project 'Sky Movies.xcodeproj'
platform :ios, '9.0'

target 'Sky Movies' do
   
  pod 'Alamofire'
  pod 'AlamofireImage'
  #pod 'SwiftyJSON'
  pod 'SwiftMessages'  

  target 'Sky MoviesTests' do

  end

end
